#!/bin/sh

### BEGIN INIT INFO
# Provides: foo
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

USER=foo
PROGRAM=/usr/local/bin/foo.py
OUTFILE=/var/log/foo/foo.out
PIDFILE=/var/run/foo.pid


start()
{
    running && echo Already running && return 1
    su -s /bin/sh \
       -c "$PROGRAM > \"$OUTFILE\" 2>&1 & echo \$!" \
       "$USER" > "$PIDFILE"
}


stop()
{
    ! running && echo Already stopped && return 1
    [ ! -w "$(dirname "$PIDFILE")" ] && echo Cannot remove "$PIDFILE" && return 1
    kill $(cat "$PIDFILE") && rm "$PIDFILE"
}


status()
{
    running && echo Running || echo Stopped
}


usage()
{
    echo "Usage: $0 {start|stop|status|restart}"
}


running()
{
    [ -f "$PIDFILE" ] && ps -o pid= -p $(cat "$PIDFILE") > /dev/null
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;
    *)
        usage
        ;;
esac
